-- V1__inital_schema.sql seeds USERS, ROLES, PERMISSIONS, and REFRESH_TOKENS with
-- explicit PK values (it's a raw dump of a real dev DB), then tries to fast-forward
-- each table's ID sequence via SELECT setval('users_id_seq', ...), etc. Those four
-- PK columns are `GENERATED BY DEFAULT AS IDENTITY`, so Postgres backs them with its
-- own internally-owned sequence (e.g. users_users_pk_seq) — NOT the manually created
-- *_id_seq sequences V1 calls setval on. The real identity sequence is therefore never
-- advanced past 1, so the very next INSERT collides with an already-seeded PK and
-- fails with a unique-constraint violation (surfaces to the frontend as a 409
-- "conflicts with existing data" error) — hit repeatedly during concurrent TestSprite
-- logins on 2026-08-30 since every login inserts a REFRESH_TOKENS row.
--
-- Fix forward: advance each real identity-owned sequence to MAX(pk)+1 based on
-- pg_get_serial_sequence, not a hardcoded number, so this stays correct regardless
-- of how many seed rows a future V1 dump ends up with.
SELECT setval(pg_get_serial_sequence('users', 'users_pk'), COALESCE((SELECT MAX(users_pk) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('roles', 'roles_pk'), COALESCE((SELECT MAX(roles_pk) FROM roles), 1), true);
SELECT setval(pg_get_serial_sequence('permissions', 'permissions_pk'), COALESCE((SELECT MAX(permissions_pk) FROM permissions), 1), true);
SELECT setval(pg_get_serial_sequence('refresh_tokens', 'refresh_tokens_pk'), COALESCE((SELECT MAX(refresh_tokens_pk) FROM refresh_tokens), 1), true);
