-- ============================================================================
-- Reconciliation Migration — DATABASE_RECONCILIATION_REPORT.md Section 6
-- Source: governance/modules/ORG/P2/db-script.md BLOCK 4 (COMMENTS).
--
-- FINDING (category GOVERNANCE_METADATA_ONLY): db-script.md defines 102
-- COMMENT ON TABLE/COLUMN statements for the 8 Organization tables. None of
-- them were ever applied by V1 (which only carries the schema, not the
-- documentation metadata dump). Schema itself is already EXACT_MATCH — this
-- migration adds ONLY the missing metadata, verbatim, no wording changes.
--
-- Identifiers lowercased to match this repo's existing Flyway house style
-- (V1/V3/V5 all use lowercase unquoted identifiers); comment text (including
-- DBF-ID/RULE-ID references and Arabic strings) is reproduced exactly as
-- authored in db-script.md — not reworded, not summarized.
-- ============================================================================

BEGIN;

-- org_legal_entity
COMMENT ON TABLE org_legal_entity IS 'الكيانات القانونية المسجلة للمنشأة — Legal entities registered in the system. ROOT entity. ENTITY-ORG-001.';
COMMENT ON COLUMN org_legal_entity.legal_entity_pk   IS 'DBF-0001 — PK. Populated by framework from ORG_LEGAL_ENTITY_SEQ.';
COMMENT ON COLUMN org_legal_entity.legal_entity_code IS 'DBF-0002 — Business code LE-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_legal_entity.name_ar           IS 'DBF-0003 — Arabic name. Unique within global scope (RULE-ORG-015).';
COMMENT ON COLUMN org_legal_entity.name_en           IS 'DBF-0004 — English name. Unique within global scope (RULE-ORG-015).';
COMMENT ON COLUMN org_legal_entity.entity_type_id    IS 'DBF-0005 — Stores LOV code. lookupKey: LEGAL_ENTITY_TYPE (LOV-ORG-001). Values: HEAD_OFFICE, BRANCH_OFFICE, SUBSIDIARY, REPRESENTATIVE_OFFICE.';
COMMENT ON COLUMN org_legal_entity.is_active_fl      IS 'DBF-0006 — 1=Active, 0=Inactive. Deactivation governed by RULE-ORG-001 and RULE-ORG-002.';
COMMENT ON COLUMN org_legal_entity.notes             IS 'DBF-0007 — Optional free-text notes.';
COMMENT ON COLUMN org_legal_entity.created_by        IS 'DBF-0008 — Audit. Populated by AuditEntityListener. Not accepted in DTO.';
COMMENT ON COLUMN org_legal_entity.created_at        IS 'DBF-0009 — Audit. Populated by AuditEntityListener. Not accepted in DTO.';
COMMENT ON COLUMN org_legal_entity.updated_by        IS 'DBF-0010 — Audit. Populated by AuditEntityListener. Not accepted in DTO.';
COMMENT ON COLUMN org_legal_entity.updated_at        IS 'DBF-0011 — Audit. Populated by AuditEntityListener. Not accepted in DTO.';

-- org_branch
COMMENT ON TABLE org_branch IS 'فروع الكيانات القانونية — Branches of legal entities. Primary DataScope boundary. ENTITY-ORG-002.';
COMMENT ON COLUMN org_branch.branch_pk       IS 'DBF-0012 — PK. Populated by framework from ORG_BRANCH_SEQ.';
COMMENT ON COLUMN org_branch.branch_code     IS 'DBF-0013 — Business code BR-[LE_CODE]-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_branch.name_ar         IS 'DBF-0014 — Arabic name. Unique within same LegalEntity (RULE-ORG-015).';
COMMENT ON COLUMN org_branch.name_en         IS 'DBF-0015 — English name. Unique within same LegalEntity (RULE-ORG-015).';
COMMENT ON COLUMN org_branch.legal_entity_fk IS 'DBF-0016 — FK to ORG_LEGAL_ENTITY. NOT NULL. Creation blocked if parent LegalEntity inactive (RULE-ORG-018).';
COMMENT ON COLUMN org_branch.branch_type_id  IS 'DBF-0017 — Stores LOV code. lookupKey: BRANCH_TYPE (LOV-ORG-002). Values: MAIN_BRANCH, SUB_BRANCH, OPERATIONS_BRANCH, ADMIN_BRANCH.';
COMMENT ON COLUMN org_branch.is_active_fl    IS 'DBF-0018 — 1=Active, 0=Inactive. Deactivation governed by RULE-ORG-003, 004, 005.';
COMMENT ON COLUMN org_branch.notes           IS 'DBF-0019 — Optional free-text notes.';
COMMENT ON COLUMN org_branch.created_by      IS 'DBF-0020 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_branch.created_at      IS 'DBF-0021 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_branch.updated_by      IS 'DBF-0022 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_branch.updated_at      IS 'DBF-0023 — Audit. Populated by AuditEntityListener.';

-- org_region_type
COMMENT ON TABLE org_region_type IS 'أنواع المناطق — Region type reference table. PRIVATE entity (owner: Organization). > 15 potential values. ENTITY-ORG-008.';
COMMENT ON COLUMN org_region_type.region_type_pk   IS 'DBF-0024 — PK. Populated by framework from ORG_REGION_TYPE_SEQ.';
COMMENT ON COLUMN org_region_type.region_type_code IS 'DBF-0025 — Unique business code. e.g. GEOGRAPHIC, SALES, OPERATIONAL.';
COMMENT ON COLUMN org_region_type.name_ar          IS 'DBF-0026 — Arabic name.';
COMMENT ON COLUMN org_region_type.name_en          IS 'DBF-0027 — English name.';
COMMENT ON COLUMN org_region_type.is_active_fl     IS 'DBF-0028 — 1=Active, 0=Inactive.';
COMMENT ON COLUMN org_region_type.created_by       IS 'DBF-0029 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_region_type.created_at       IS 'DBF-0030 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_region_type.updated_by       IS 'DBF-0031 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_region_type.updated_at       IS 'DBF-0032 — Audit. Populated by AuditEntityListener.';

-- org_region
COMMENT ON TABLE org_region IS 'المناطق الجغرافية / المبيعاتية — Regions linked to a legal entity. ENTITY-ORG-003. OQ-001: SOFT-READ impact on deactivation — DEFERRED.';
COMMENT ON COLUMN org_region.region_pk         IS 'DBF-0033 — PK. Populated by framework from ORG_REGION_SEQ.';
COMMENT ON COLUMN org_region.region_code       IS 'DBF-0034 — Business code RG-[LE_CODE]-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_region.name_ar           IS 'DBF-0035 — Arabic name. Unique within same LegalEntity (RULE-ORG-015).';
COMMENT ON COLUMN org_region.name_en           IS 'DBF-0036 — English name. Unique within same LegalEntity (RULE-ORG-015).';
COMMENT ON COLUMN org_region.legal_entity_fk   IS 'DBF-0037 — FK to ORG_LEGAL_ENTITY. NOT NULL.';
COMMENT ON COLUMN org_region.region_type_id_fk IS 'DBF-0038 — FK to ORG_REGION_TYPE. NOT NULL.';
COMMENT ON COLUMN org_region.is_active_fl      IS 'DBF-0039 — 1=Active, 0=Inactive. Deactivation governed by RULE-ORG-006 (active branches check) and RULE-ORG-017 (SOFT-READ consumer warning). OQ-001 DEFERRED.';
COMMENT ON COLUMN org_region.notes             IS 'DBF-0040 — Optional free-text notes.';
COMMENT ON COLUMN org_region.created_by        IS 'DBF-0041 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_region.created_at        IS 'DBF-0042 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_region.updated_by        IS 'DBF-0043 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_region.updated_at        IS 'DBF-0044 — Audit. Populated by AuditEntityListener.';

-- org_department
COMMENT ON TABLE org_department IS 'الأقسام — Hierarchical department tree per branch. ENTITY-ORG-004. Nodes: SUMMARY (aggregate) / DETAIL (leaf). Circular reference prevented by RULE-ORG-007.';
COMMENT ON COLUMN org_department.department_pk        IS 'DBF-0045 — PK. Populated by framework from ORG_DEPARTMENT_SEQ.';
COMMENT ON COLUMN org_department.department_code      IS 'DBF-0046 — Business code DEP-[BR_CODE]-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_department.name_ar              IS 'DBF-0047 — Arabic name. Unique within same Branch (RULE-ORG-015).';
COMMENT ON COLUMN org_department.name_en              IS 'DBF-0048 — English name. Unique within same Branch (RULE-ORG-015).';
COMMENT ON COLUMN org_department.branch_fk            IS 'DBF-0049 — FK to ORG_BRANCH. NOT NULL. Creation blocked if Branch inactive (RULE-ORG-019).';
COMMENT ON COLUMN org_department.parent_department_fk IS 'DBF-0050 — Self-reference FK to ORG_DEPARTMENT. NULLABLE (root nodes have no parent). Circular reference blocked by RULE-ORG-007.';
COMMENT ON COLUMN org_department.node_type_id         IS 'DBF-0051 — lookupKey: DEPARTMENT_NODE_TYPE (LOV-ORG-003). Values: SUMMARY, DETAIL. Immutable after first save (RULE-ORG-020). SUMMARY nodes cannot be assigned to transactional records (RULE-ORG-009).';
COMMENT ON COLUMN org_department.is_active_fl         IS 'DBF-0052 — 1=Active, 0=Inactive.';
COMMENT ON COLUMN org_department.notes                IS 'DBF-0053 — Optional free-text notes.';
COMMENT ON COLUMN org_department.created_by           IS 'DBF-0054 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_department.created_at           IS 'DBF-0055 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_department.updated_by           IS 'DBF-0056 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_department.updated_at           IS 'DBF-0057 — Audit. Populated by AuditEntityListener.';

-- org_cost_center
COMMENT ON TABLE org_cost_center IS 'مراكز التكلفة — Hierarchical cost center tree per branch. ENTITY-ORG-005. Nodes: SUMMARY / DETAIL. Finance (3.4) primary consumer via HARD-FK.';
COMMENT ON COLUMN org_cost_center.cost_center_pk        IS 'DBF-0058 — PK. Populated by framework from ORG_COST_CENTER_SEQ.';
COMMENT ON COLUMN org_cost_center.cost_center_code      IS 'DBF-0059 — Business code CC-[BR_CODE]-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_cost_center.name_ar               IS 'DBF-0060 — Arabic name. Unique within same Branch (RULE-ORG-015).';
COMMENT ON COLUMN org_cost_center.name_en               IS 'DBF-0061 — English name. Unique within same Branch (RULE-ORG-015).';
COMMENT ON COLUMN org_cost_center.branch_fk             IS 'DBF-0062 — FK to ORG_BRANCH. NOT NULL. Creation blocked if Branch inactive (RULE-ORG-019).';
COMMENT ON COLUMN org_cost_center.parent_cost_center_fk IS 'DBF-0063 — Self-reference FK to ORG_COST_CENTER. NULLABLE (root nodes have no parent). Circular reference blocked by RULE-ORG-008.';
COMMENT ON COLUMN org_cost_center.node_type_id          IS 'DBF-0064 — lookupKey: COST_CENTER_NODE_TYPE (LOV-ORG-004). Values: SUMMARY, DETAIL. Immutable after first save (RULE-ORG-020). SUMMARY nodes cannot be assigned to transactional records (RULE-ORG-010).';
COMMENT ON COLUMN org_cost_center.cost_center_type_id   IS 'DBF-0065 — lookupKey: COST_CENTER_TYPE (LOV-ORG-005). Values: DIRECT, INDIRECT, SHARED.';
COMMENT ON COLUMN org_cost_center.is_active_fl          IS 'DBF-0066 — 1=Active, 0=Inactive.';
COMMENT ON COLUMN org_cost_center.notes                 IS 'DBF-0067 — Optional free-text notes.';
COMMENT ON COLUMN org_cost_center.created_by            IS 'DBF-0068 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_cost_center.created_at            IS 'DBF-0069 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_cost_center.updated_by            IS 'DBF-0070 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_cost_center.updated_at            IS 'DBF-0071 — Audit. Populated by AuditEntityListener.';

-- org_profit_center
COMMENT ON TABLE org_profit_center IS 'مراكز الربح — Profit centers linked to a legal entity. ENTITY-ORG-006. Owned by Organization — consumed by Finance (3.4) via HARD-FK.';
COMMENT ON COLUMN org_profit_center.profit_center_pk   IS 'DBF-0072 — PK. Populated by framework from ORG_PROFIT_CENTER_SEQ.';
COMMENT ON COLUMN org_profit_center.profit_center_code IS 'DBF-0073 — Business code PC-[LE_CODE]-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_profit_center.name_ar            IS 'DBF-0074 — Arabic name. Unique within same LegalEntity (RULE-ORG-015).';
COMMENT ON COLUMN org_profit_center.name_en            IS 'DBF-0075 — English name. Unique within same LegalEntity (RULE-ORG-015).';
COMMENT ON COLUMN org_profit_center.legal_entity_fk    IS 'DBF-0076 — FK to ORG_LEGAL_ENTITY. NOT NULL.';
COMMENT ON COLUMN org_profit_center.is_active_fl       IS 'DBF-0077 — 1=Active, 0=Inactive. No internal deactivation constraints (RULE-ORG-002 applies at LegalEntity level).';
COMMENT ON COLUMN org_profit_center.notes              IS 'DBF-0078 — Optional free-text notes.';
COMMENT ON COLUMN org_profit_center.created_by         IS 'DBF-0079 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_profit_center.created_at         IS 'DBF-0080 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_profit_center.updated_by         IS 'DBF-0081 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_profit_center.updated_at         IS 'DBF-0082 — Audit. Populated by AuditEntityListener.';

-- org_location_site
COMMENT ON TABLE org_location_site IS 'مواقع العمل — Physical work locations per branch. ENTITY-ORG-007. L1 physical location concept consumed by Inventory (3.2) via HARD-FK.';
COMMENT ON COLUMN org_location_site.location_site_pk   IS 'DBF-0083 — PK. Populated by framework from ORG_LOCATION_SITE_SEQ.';
COMMENT ON COLUMN org_location_site.location_site_code IS 'DBF-0084 — Business code LS-[BR_CODE]-NNNNN. Generated by NumberingEngine. Immutable after first save.';
COMMENT ON COLUMN org_location_site.name_ar            IS 'DBF-0085 — Arabic name. Unique within same Branch (RULE-ORG-015).';
COMMENT ON COLUMN org_location_site.name_en            IS 'DBF-0086 — English name. Unique within same Branch (RULE-ORG-015).';
COMMENT ON COLUMN org_location_site.branch_fk          IS 'DBF-0087 — FK to ORG_BRANCH. NOT NULL. Creation blocked if Branch inactive (RULE-ORG-019).';
COMMENT ON COLUMN org_location_site.site_type_id       IS 'DBF-0088 — Stores LOV code. lookupKey: LOCATION_SITE_TYPE (LOV-ORG-006). Values: OFFICE, WAREHOUSE, FACTORY, SITE, RETAIL.';
COMMENT ON COLUMN org_location_site.is_active_fl       IS 'DBF-0089 — 1=Active, 0=Inactive.';
COMMENT ON COLUMN org_location_site.notes              IS 'DBF-0090 — Optional free-text notes.';
COMMENT ON COLUMN org_location_site.created_by         IS 'DBF-0091 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_location_site.created_at         IS 'DBF-0092 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_location_site.updated_by         IS 'DBF-0093 — Audit. Populated by AuditEntityListener.';
COMMENT ON COLUMN org_location_site.updated_at         IS 'DBF-0094 — Audit. Populated by AuditEntityListener.';

COMMIT;
