package com.erp.security.mapper;

import com.erp.security.dto.PermissionResponse;
import com.erp.security.entity.Permission;
import org.springframework.stereotype.Component;

/**
 * Manual entity/DTO mapper for ENTITY-SEC-003 (Permission). Read-only: permissions are
 * system-generated by PermissionGenerationDomainService (RULE-SEC-011), never client-created or
 * client-updated, so only toResponse is provided (no toEntity/updateEntityFromRequest — there is
 * no create/update DTO for this entity). pageFk is read off the (lazy) page association.
 */
@Component
public class PermissionMapper {

    public PermissionResponse toResponse(Permission entity) {
        if (entity == null) {
            return null;
        }
        return PermissionResponse.builder()
            .id(entity.getId())
            .permissionCode(entity.getPermissionCode())
            .permissionType(entity.getPermissionType())
            .nameAr(entity.getNameAr())
            .nameEn(entity.getNameEn())
            .isActiveFl(Boolean.TRUE.equals(entity.getIsActive()))
            .pageFk(entity.getPage() != null ? entity.getPage().getId() : null)
            .createdAt(entity.getCreatedAt())
            .createdBy(entity.getCreatedBy())
            .updatedAt(entity.getUpdatedAt())
            .updatedBy(entity.getUpdatedBy())
            .build();
    }
}
