package com.example.erp.org.domain;

import com.example.erp.common.domain.status.Status;
import com.example.erp.common.exception.LocalizedException;
import com.example.erp.org.entity.OrgLegalEntity;
import com.example.erp.org.exception.OrgErrorCodes;

/**
 * Business Rule owner for {@link OrgLegalEntity}. Plain class — no Spring/JPA, no Repository
 * access. Constructed only via {@code create()}/{@code from()}. See {@code domain-layer.md}.
 */
public final class OrgLegalEntityDomain {

    private final String legalEntityCode;
    private final boolean active;

    private OrgLegalEntityDomain(String legalEntityCode, boolean active) {
        this.legalEntityCode = legalEntityCode;
        this.active = active;
    }

    /**
     * Construction-time validation for a new LegalEntity. The code itself is generated by the
     * NumberingEngine (RULE-ORG-013) before this is called — this only guards against a blank
     * result reaching persistence.
     */
    public static OrgLegalEntityDomain create(String generatedCode) {
        if (generatedCode == null || generatedCode.isBlank()) {
            throw new LocalizedException(Status.VALIDATION_ERROR, "validation.required", "legalEntityCode");
        }
        return new OrgLegalEntityDomain(generatedCode, true);
    }

    public static OrgLegalEntityDomain from(OrgLegalEntity entity) {
        return new OrgLegalEntityDomain(entity.getLegalEntityCode(), Boolean.TRUE.equals(entity.getIsActiveFl()));
    }

    public String getLegalEntityCode() {
        return legalEntityCode;
    }

    public boolean isActive() {
        return active;
    }

    /**
     * RULE-ORG-001 / RULE-ORG-002 — decision only; the Service performs
     * {@code entity.deactivate()} after this returns without throwing.
     */
    public void assertCanDeactivate(long activeBranchCount, long activeProfitCenterCount) {
        if (activeBranchCount > 0) {
            throw new LocalizedException(Status.BUSINESS_RULE_VIOLATION, OrgErrorCodes.LE_HAS_ACTIVE_BRANCHES);
        }
        if (activeProfitCenterCount > 0) {
            throw new LocalizedException(Status.BUSINESS_RULE_VIOLATION, OrgErrorCodes.LE_HAS_ACTIVE_PROFIT_CENTERS);
        }
    }
}
